osx_image: xcode7
language: objective-c
xcode_project: "./build/cocos2d_libs.xcodeproj"
xcode_scheme: "libcocos2d iOS"

before_install:
  - python download-deps.py

# whitelist
branches:
  only:
    - tvos
